# Generated by Django 3.1.4 on 2020-12-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0004_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255)),
            ],
        ),
    ]
