# Generated by Django 3.1.4 on 2020-12-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('team', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pick',
            name='status',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
