# Generated by Django 3.1.4 on 2020-12-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0007_auto_20201218_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='status',
            field=models.CharField(default='In', max_length=50),
        ),
    ]
