# Generated by Django 3.1.4 on 2020-12-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0008_auto_20201218_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='status',
        ),
    ]
