# Generated by Django 3.1.4 on 2020-12-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0009_remove_pick_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.TextField(default='In'),
        ),
    ]
